# Generated by Django 2.2.13 on 2020-06-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='img',
            field=models.ImageField(upload_to='demo/%Y/%m/%d'),
        ),
    ]
