# Generated by Django 2.2.13 on 2020-06-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='油箱')),
                ('nickname', models.CharField(max_length=8, verbose_name='昵称')),
                ('icon', models.ImageField(upload_to='icon/%Y/%m/%d', verbose_name='头像')),
            ],
        ),
    ]
