# Generated by Django 2.2.13 on 2020-06-21 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='邮箱'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='数量')),
                ('is_select', models.BooleanField(default=True, verbose_name='选中')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Book', verbose_name='书籍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.User', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '购物车',
            },
        ),
    ]
