# Generated by Django 2.2.13 on 2020-06-28 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_auto_20200628_0548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collect',
            old_name='user_id',
            new_name='user',
        ),
    ]
