# Generated by Django 2.2.13 on 2020-06-28 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20200628_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('content', models.CharField(max_length=200, verbose_name='评论')),
                ('zan', models.IntegerField(default=0, verbose_name='点赞')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Book', verbose_name='书籍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.User', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('content', models.CharField(max_length=200, verbose_name='评论')),
                ('zan', models.IntegerField(default=0, verbose_name='点赞')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Comment', verbose_name='评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.User', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '评论回复',
            },
        ),
    ]
